"""
Custom Prometheus metrics for model quality and data drift monitoring.

This module provides:
- Model accuracy metrics (Hit@20) loaded from eval_results.json
- Data drift metrics loaded from drift_report.json
- One-time metric initialization at Flask app startup (no background thread)

Note: Metrics are created without a registry and will be registered
when init_metrics() is called with the app's registry.
"""

import os
import json
from prometheus_client import Gauge

# Metrics will be initialized in init_metrics()
model_hit_at_20 = None
data_drift_rating_psi = None
data_drift_movie_popularity_gini = None
data_drift_top10_share = None
data_drift_top100_share = None
data_drift_one_and_done_share = None
data_drift_detected = None


def init_metrics(registry):
    """
    Initialize metrics with the given registry.
    Must be called before load_metrics_from_artifacts().

    Args:
        registry: Prometheus CollectorRegistry to use
    """
    global model_hit_at_20, data_drift_rating_psi, data_drift_movie_popularity_gini
    global data_drift_top10_share, data_drift_top100_share, data_drift_one_and_done_share
    global data_drift_detected

    # Skip if already initialized (prevents duplicate registration in tests)
    if model_hit_at_20 is not None:
        return

    # Model quality metrics
    model_hit_at_20 = Gauge(
        'model_hit_at_20',
        'Hit@20 accuracy metric for the recommendation model',
        registry=registry
    )

    # Data drift metrics
    data_drift_rating_psi = Gauge(
        'data_drift_rating_psi',
        'Population Stability Index for rating distribution (>0.1=moderate, >0.25=strong drift)',
        registry=registry
    )

    data_drift_movie_popularity_gini = Gauge(
        'data_drift_movie_popularity_gini',
        'Gini coefficient for movie popularity concentration (>0.9=extreme concentration)',
        registry=registry
    )

    data_drift_top10_share = Gauge(
        'data_drift_top10_share',
        'Share of interactions for top 10 movies',
        registry=registry
    )

    data_drift_top100_share = Gauge(
        'data_drift_top100_share',
        'Share of interactions for top 100 movies',
        registry=registry
    )

    data_drift_one_and_done_share = Gauge(
        'data_drift_one_and_done_share',
        'Share of users with only one interaction',
        registry=registry
    )

    data_drift_detected = Gauge(
        'data_drift_detected',
        'Boolean flag indicating if drift was detected (1=drift, 0=no drift)',
        registry=registry
    )


def load_metrics_from_artifacts(model_dir="/app/models"):
    """
    Load pre-calculated metrics from model artifacts.
    Reads drift_report.json and eval_results.json from the MODEL directory.
    
    IMPORTANT: These files are generated by the retraining pipeline and stored
    alongside the trained model in /app/models (mounted from ~/models/latest/),
    NOT in /app/artifacts (which contains static reference data).
    
    Called once at Flask app startup.

    Args:
        model_dir: Directory containing model artifacts (default: /app/models)
    """
    print(f"Loading metrics from {model_dir}...")

    try:
        # Load Hit@20 from eval_results.json
        eval_path = os.path.join(model_dir, "eval_results.json")
        if os.path.exists(eval_path):
            with open(eval_path) as f:
                eval_data = json.load(f)
                hit_at_20_value = eval_data.get('hit_at_20', 0.0)
                model_hit_at_20.set(hit_at_20_value)
                print(f"  ✓ Hit@20: {hit_at_20_value:.4f}")
        else:
            print(f"  ⚠️  eval_results.json not found")
            print(f"     Path: {eval_path}")
            model_hit_at_20.set(0.0)

        # Load drift metrics from drift_report.json
        drift_path = os.path.join(model_dir, "drift_report.json")
        if os.path.exists(drift_path):
            with open(drift_path) as f:
                drift_data = json.load(f)
                metrics = drift_data.get('metrics', {})

                # Rating PSI (only in reference-vs-current mode)
                if 'rating_psi' in metrics:
                    psi_value = metrics['rating_psi'].get('psi', 0.0)
                    data_drift_rating_psi.set(psi_value)
                    print(f"  ✓ Rating PSI: {psi_value:.4f}")
                else:
                    data_drift_rating_psi.set(0.0)

                # Movie popularity metrics
                if 'movie_popularity' in metrics:
                    pop = metrics['movie_popularity']

                    # Handle both modes
                    if 'cur' in pop:  # reference-vs-current
                        gini = pop['cur'].get('gini_movies', 0.0)
                        top10 = pop['cur'].get('top10_share', 0.0)
                        top100 = pop['cur'].get('top100_share', 0.0)
                    else:  # single-snapshot mode
                        gini = pop.get('gini_movies', 0.0)
                        top10 = pop.get('top10_share', 0.0)
                        top100 = pop.get('top100_share', 0.0)

                    data_drift_movie_popularity_gini.set(gini)
                    data_drift_top10_share.set(top10)
                    data_drift_top100_share.set(top100)

                    print(f"  ✓ Gini Coefficient: {gini:.4f}")
                    print(f"  ✓ Top 10 Share: {top10:.4f}")
                    print(f"  ✓ Top 100 Share: {top100:.4f}")
                else:
                    data_drift_movie_popularity_gini.set(0.0)
                    data_drift_top10_share.set(0.0)
                    data_drift_top100_share.set(0.0)

                # User activity metrics
                if 'user_activity' in metrics:
                    user_act = metrics['user_activity']
                    if 'cur' in user_act:
                        one_and_done = user_act['cur'].get('one_and_done_share', 0.0)
                    else:
                        one_and_done = user_act.get('one_and_done_share', 0.0)
                    data_drift_one_and_done_share.set(one_and_done)
                    print(f"  ✓ One-and-Done Share: {one_and_done:.4f}")
                else:
                    data_drift_one_and_done_share.set(0.0)

                # Drift detected flag
                drift_detected_value = 1.0 if drift_data.get('drift_detected', False) else 0.0
                data_drift_detected.set(drift_detected_value)
                print(f"  ✓ Drift Detected: {drift_detected_value}")
        else:
            print(f"  ⚠️  drift_report.json not found")
            print(f"     Path: {drift_path}")
            # Set all drift metrics to 0
            data_drift_rating_psi.set(0.0)
            data_drift_movie_popularity_gini.set(0.0)
            data_drift_top10_share.set(0.0)
            data_drift_top100_share.set(0.0)
            data_drift_one_and_done_share.set(0.0)
            data_drift_detected.set(0.0)

        print("✅ Metrics loaded successfully from model artifacts")

    except Exception as e:
        print(f"❌ Error loading metrics from artifacts: {e}")
        import traceback
        traceback.print_exc()
        # Set default values on error
        model_hit_at_20.set(0.0)
        data_drift_rating_psi.set(0.0)
        data_drift_movie_popularity_gini.set(0.0)
        data_drift_top10_share.set(0.0)
        data_drift_top100_share.set(0.0)
        data_drift_one_and_done_share.set(0.0)
        data_drift_detected.set(0.0)
